name: Update Robo in Homebrew
on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Version to upload'
        required: true
        default: 'x.x.x'
jobs:
  robo:
    name: robo
    runs-on: ubuntu-latest
    steps:
      - name: main checkout
        uses: actions/checkout@v3
      - name: setup invoke
        run: pipx install invoke
      - name: homebrew cask checkout
        uses: actions/checkout@v3
        with:
          ssh-key: ${{ secrets.CASK_REPO_KEY }}
          repository: robocorp/homebrew-tools
          path: ./cli/cask

      - name: configure homebrew cask git
        run: |
          cd ./cli/cask
          git config user.name Kerkko Pelttari
          git config user.email kerkko@robocorp.com

      - name: download latest rcc
        run: |
          mkdir -p cli/dist/macos64/
          version_number=${{github.event.inputs.name}}
          curl "https://downloads.robocorp.com/robo/releases/${version_number}/macos64/robo" -o cli/dist/macos64/robo

      - name: package cask
        run: cd cli && invoke macos-push-brew dist/macos64/robo ${{github.event.inputs.name}}
