name: Library tests

on:
  push:
    branches: ["master"]
    paths: ["libs/**/", ".github/workflows/tests_libs.yml"]
  pull_request:
    branches: ["master"]
    paths: ["libs/**/", ".github/workflows/tests_libs.yml"]

defaults:
  run:
    working-directory: './libs'


jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        include:
          - name: "ubuntu-py310"
            python: "3.10"
            os: ubuntu-latest
          - name: "windows-py310"
            python: "3.10"
            os: windows-latest
          - name: "macos-py310"
            os: macos-latest


    steps:
    - name: Checkout repository and submodules
      uses: actions/checkout@v2

    - uses: browser-actions/setup-firefox@v1
    - run: firefox --version

    - uses: browser-actions/setup-chrome@v1
    - run: chrome --version

    - name: Install poetry
      run: pipx install poetry

    - name: Set up Python ${{ matrix.python }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python }}
        cache: 'poetry'

    - name: Install project
      run: poetry install
    - name: Test
      env:
        PYTHONPATH: .
      run: poetry run pytest
