name: Tests

on:
  push:
    branches: [master]
    paths: [core]
  pull_request:
    branches: [master]
    paths: [core]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        name: [
          "ubuntu-py310",
          "windows-py310",
        ]

        include:
          - name: "ubuntu-py310"
            python: "3.10"
            os: ubuntu-latest
          - name: "windows-py310"
            python: "3.10"
            os: windows-latest


    steps:
    - name: Checkout repository and submodules
      uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python }}
        cache: 'poetry'
    - name: Install poetry
      working-directory: ./core
      run: |
        python -m pip install --upgrade pip
        pip install poetry
        poetry install
    - name: Test
      working-directory: ./core
      env:
        PYTHONPATH: ./core/src
      run: poetry run pytest -rfE -vv tests/robo_tests

